#端口号
server:
  port: 9003

#数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.78.128.136:3307/tensquare_qa?useunicode=true&characterEncoding=utf8
    username: root
    password: 1234
  application: Qa

#Mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.clm.Bean
#日志
logging:
  level:
    org:
      clm:
        Dao: debug

#分页
pagehelper:
  auto-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql

