#端口号
server:
  port: 9006

#数据源
spring:
  application:
    name: Qa
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.78.128.136:3307/tensquare_qa?useunicode=true&characterEncoding=utf8
    username: root
    password: 1234
  rabbitmq:
    host: 129.204.28.226

#Mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.clm.Bean
#日志
logging:
  level:
    org:
      clm:
        Dao: debug

#分页
pagehelper:
  auto-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:6868/eureka/
  instance:
    prefer-ip-address: true
    appname: Qa
    hostname: 120.78.128.136
feign:
  hystrix:
    enabled: true
