#端口号
server:
  port: 9002
eureka:
  client:
    service-url:
      defaultZone: http://120.78.128.136:6868/eureka/
    eureka-server-port: 6868
    fetch-registry: true
  instance:
    prefer-ip-address: true
    appname: Base
    hostname: localhost

#数据源
spring:
  application:
    name: Base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.78.128.136:3307/tensquare_base?useunicode=true&characterEncoding=utf8
    username: root
    password: 1234


#Mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.clm.Bean

#日志
logging:
  level:
    org:
      clm:
        Dao: debug

#分页
pagehelper:
  auto-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql
