#端口号
server:
  port: 9008
#数据源
spring:
  application: Search
  data:
    elasticsearch:
      cluster-nodes: 129.204.28.226:9300
#日志
logging:
  level:
    org:
      clm:
        Dao: debug

eureka:
  client:
    service-url:
      defaultZone: http://120.78.128.136:6868/eureka
  instance:
    prefer-ip-address: true
    appname: Search

